### ISSUE TITLE
still get transaction /*

### ISSUE THREAD

**Issue by piggyman007** [AfterShip/koa-newrelic#1]
Hi all,

i have tried to use koa-newrelic but still get /\* for all transactions.
currently i am using
- koa
- koa-router

i configure koa-newrelic from the example of this repo.
are there more configuration?

**Comment by aobo-y** [comment]
hi @piggyman007, first, sorry for late reply.

This project actually takes use of `this._matchedRoute` added by `koa-router` to define the most specific route for newrelic. However, `koa-router` itself have some bugs with defining the route, which you can refer here https://github.com/alexmingoia/koa-router/issues/246

see if your router config is related to this issue, or you can post your router here and see if we can help

**Comment by piggyman007** [comment]
hi i have created my own custom newrelic and it works fine now
