### ISSUE TITLE
Possibility to config errors

### ISSUE THREAD

**Issue by Ajaxy** [AfterShip/koa-newrelic#13]
Is it possible to somehow configure which errors should be reported? For example, I'd like to skip **4xx** errors from reporting. Also would be great to include additional headers/request params to error parameters. Thanks.

**Comment by eric4545** [comment]
Hi @Ajaxy, as newrelic has official support for koa [node-newrelic-koa](https://github.com/newrelic/node-newrelic-koa), we may not develop more feature on this.

And for skip 4xx for reporting you can update the newrelic.js [Newrelic Docs](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#error_ignore)
```javascript
exports.config = {
	error_collector: {
		ignore_status_codes: [200, 429]
	}
};
```

**Comment by Ajaxy** [comment]
Thanks
