### ISSUE TITLE
Tests are currently failing

### ISSUE THREAD

**Issue by avindra** [AfterShip/koa-newrelic#5]
`npm test` is showing 5 failing tests.

Are the tests simply out of date? I can help w/ travis integration if you are interested.

Also, is there any plan to add support for the Koa 2 alpha?

**Comment by aobo-y** [comment]
will check the failing tests asap (at least i don't expect it out of date 🤣 )

wow, it will be super awesome if u'd like to help on the travis

no specific plan to support Koa 2 until Node 8. 
however since it should merely be a rewrite with promise, may give it an improvised shot

**Comment by aobo-y** [comment]
@avindra hi, pls note i have updated the tests with newrelic internal stub-api & sinon
now all tests passed

https://travis-ci.org/AfterShip/koa-newrelic/builds/194690137

**Comment by avindra** [comment]
Awesome ! Thank you @yangaobo . I'll look at koa 2 if I have time. Thanks for merging and addressing this
